version: '3'

services:
  docker-wordpress-new-db:
    image: ${DOCKER_WORDPRESS_DB_IMAGE:-mysql}:${DOCKER_WORDPRESS_DB_VERSION:-latest}
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: ${DOCKER_WORDPRESS_DB_CONTAINER_NAME}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${DOCKER_WORDPRESS_MYSQL_CPU_LIMIT:-'0.5'}
          memory: ${DOCKER_WORDPRESS_MYSQL_MEMORY_LIMIT:-300M}
    networks:
      - docker-wordpress-db-net
    volumes:
      - ${DOCKER_WORDPRESS_DB_FILES}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_WORDPRESS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_WORDPRESS_MYSQL_DATABASE}
      MYSQL_USER: ${DOCKER_WORDPRESS_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_WORDPRESS_MYSQL_PASSWORD}
    logging:
      driver: ${DOCKER_WORDPRESS_DB_LOG_DRIVER:-json-file}
      options:
        max-size: ${DOCKER_WORDPRESS_DB_LOG_MAX_SIZE:-1m}
        max-file: ${DOCKER_WORDPRESS_DB_LOG_MAX_FILE:-10}


  docker-wordpress-new-site:
    depends_on:
      - docker-wordpress-new-db
    image: ${DOCKER_WORDPRESS_SITE_IMAGE:-wordpress}:${DOCKER_WORDPRESS_SITE_VERSION:-latest}
    container_name: ${DOCKER_WORDPRESS_SITE_CONTAINER_NAME}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${DOCKER_WORDPRESS_SITE_CPU_LIMIT:-'0.5'}
          memory: ${DOCKER_WORDPRESS_SITE_MEMORY_LIMIT:-300M}
    networks:
      - docker-wordpress-proxy-network
      - docker-wordpress-db-net
    volumes:
      - ${DOCKER_WORDPRESS_SITE_FILES}:/var/www/html
      - ./conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WORDPRESS_DB_HOST: ${DOCKER_WORDPRESS_DB_HOST:-docker-wordpress-new-db}:3306
      WORDPRESS_DB_NAME: ${DOCKER_WORDPRESS_MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${DOCKER_WORDPRESS_MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${DOCKER_WORDPRESS_MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${DOCKER_WORDPRESS_TABLE_PREFIX}
      VIRTUAL_HOST: ${DOCKER_WORDPRESS_DOMAINS}
      LETSENCRYPT_HOST: ${DOCKER_WORDPRESS_DOMAINS}
      LETSENCRYPT_EMAIL: ${DOCKER_WORDPRESS_LETSENCRYPT_EMAIL}

    logging:
      driver: ${DOCKER_WORDPRESS_SITE_LOG_DRIVER:-json-file}
      options:
        max-size: ${DOCKER_WORDPRESS_SITE_LOG_MAX_SIZE:-2m}
        max-file: ${DOCKER_WORDPRESS_SITE_LOG_MAX_FILE:-10}
    extra_hosts:
      # HOST_SERVER_IP env comes from my bash.bashrc 
      # TODO: Work with server_automation scripts to make this part of the package instead of manual env var.
      ${DOCKER_WORDPRESS_DOMAINS}: ${HOST_SERVER_IP}


  wpcli:
    image: wordpress:cli
    environment:
      WORDPRESS_DB_HOST: ${DOCKER_WORDPRESS_DB_HOST:-docker-wordpress-new-db}:3306
      WORDPRESS_DB_NAME: ${DOCKER_WORDPRESS_MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${DOCKER_WORDPRESS_MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${DOCKER_WORDPRESS_MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${DOCKER_WORDPRESS_TABLE_PREFIX}
    networks:
      - docker-wordpress-db-net
    volumes:
      - ${DOCKER_WORDPRESS_SITE_FILES}:/var/www/html
    depends_on:
      - docker-wordpress-new-db
    entrypoint: wp

networks:
  docker-wordpress-proxy-network:
    external: true
  docker-wordpress-db-net:

